### GET ALL ITEMS
GET http://127.0.0.1:5000/items HTTP/1.1


### GET SINGLE ITEM
GET http://127.0.0.1:5000/items/3 HTTP/1.1


### Add ITEM
POST http://127.0.0.1:5000/items HTTP/1.1
Content-Type: application/json

{
  "name": "Add other new item"
}


### DELETE ITEM
DELETE http://127.0.0.1:5000/items/3 HTTP/1.1


### UPDATE ITEM
PUT http://127.0.0.1:5000/items/1 HTTP/1.1
Content-Type: application/json

{
  "name": "This is an updated item"
}
